title = "config"
[server]
enable = true
model_path = "./model.py"
requirements_path = "./requirements.txt"

[run]
enable = false
model_path = "./model.py"
requirements_path = "./requirements.txt"
data_source = "kuula.ai/prj-id/data-bucket"